version: '3.8'
services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    user: "1000:1000"
    volumes:
      - ./backend:/app
    environment:
      # Force the "home" to somewhere writable. For example:
      - HOME=/tmp

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    user: "1000:1000"
    volumes:
      - ./frontend:/app
    
    # environment:
    #   - VITE_BACKEND_URL=http://localhost:8000
